// ruoyi-ui/src/views/system/menu/index.vue
<template>
  <div class="app-container">
    <el-form :model="queryParams" ref="queryForm" size="small" :inline="true" v-show="showSearch">
      <el-form-item :label="menuNameLabel" prop="menuName">
        <el-input
          v-model="queryParams.menuName"
          :placeholder="menuNamePlaceholder"
          clearable
          @keyup.enter.native="handleQuery"
        />
      </el-form-item>
      <el-form-item label="状态" prop="status">
        <el-select v-model="queryParams.status" placeholder="菜单状态" clearable>
          <el-option
            v-for="dict in dict.type.sys_normal_disable"
            :key="dict.value"
            :label="dict.label"
            :value="dict.value"
          />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" icon="el-icon-search" size="mini" @click="handleQuery">{{ $t('common.search') }}</el-button>
        <el-button icon="el-icon-refresh" size="mini" @click="resetQuery">{{ $t('common.reset') }}</el-button>
      </el-form-item>
    </el-form>

    <el-row :gutter="10" class="mb8">
      <el-col :span="1.5">
        <el-button
          type="primary"
          plain
          icon="el-icon-plus"
          size="mini"
          @click="handleAdd"
          v-hasPermi="['system:menu:add']"
        >{{ $t('common.add') }}</el-button>
      </el-col>
      <el-col :span="1.5">
        <el-button
          type="info"
          plain
          icon="el-icon-sort"
          size="mini"
          @click="toggleExpandAll"
        >{{ $t('common.expandCollapse') }}</el-button>
      </el-col>
      <right-toolbar :showSearch.sync="showSearch" @queryTable="getList"></right-toolbar>
    </el-row>

    <el-table
      v-if="refreshTable"
      v-loading="loading"
      :data="menuList"
      row-key="menuId"
      :default-expand-all="isExpandAll"
      :tree-props="{children: 'children', hasChildren: 'hasChildren'}"
    >
      <el-table-column :label="menuNameLabel" :show-overflow-tooltip="true" width="180">
        <template slot-scope="scope">
          {{ displayMenuName(scope.row) }}
        </template>
      </el-table-column>
      <el-table-column prop="icon" label="图标" align="center" width="100">
        <template slot-scope="scope">
          <svg-icon :icon-class="scope.row.icon" />
        </template>
      </el-table-column>
      <el-table-column prop="orderNum" label="排序" width="60"></el-table-column>
      <el-table-column prop="perms" label="权限标识" :show-overflow-tooltip="true"></el-table-column>
      <el-table-column prop="component" label="组件路径" :show-overflow-tooltip="true"></el-table-column>
      <el-table-column prop="status" :label="$t('common.status')" width="80">
        <template slot-scope="scope">
          <dict-tag :options="dict.type.sys_normal_disable" :value="scope.row.status"/>
        </template>
      </el-table-column>
      <el-table-column :label="$t('common.createTime')" align="center" prop="createTime">
        <template slot-scope="scope">
          <span>{{ parseTime(scope.row.createTime) }}</span>
        </template>
      </el-table-column>
      <el-table-column :label="$t('common.operation')" align="center" class-name="small-padding fixed-width">
        <template slot-scope="scope">
          <el-button
            size="mini"
            type="text"
            icon="el-icon-edit"
            @click="handleUpdate(scope.row)"
            v-hasPermi="['system:menu:edit']"
          >{{ $t('common.edit') }}</el-button>
          <el-button
            size="mini"
            type="text"
            icon="el-icon-plus"
            @click="handleAdd(scope.row)"
            v-hasPermi="['system:menu:add']"
          >{{ $t('common.add') }}</el-button>
          <el-button
            size="mini"
            type="text"
            icon="el-icon-delete"
            @click="handleDelete(scope.row)"
            v-hasPermi="['system:menu:remove']"
          >{{ $t('common.delete') }}</el-button>
        </template>
      </el-table-column>
    </el-table>

    <!-- 添加或修改菜单对话框 -->
    <el-dialog :title="title" :visible.sync="open" width="680px" append-to-body>
      <el-form ref="form" :model="form" :rules="rules" label-width="100px">
        <el-row>
          <el-col :span="24">
            <el-form-item label="上级菜单" prop="parentId">
              <treeselect
                v-model="form.parentId"
                :options="menuOptions"
                :normalizer="normalizer"
                :show-count="true"
                placeholder="选择上级菜单"
              />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="24">
            <el-form-item label="菜单类型" prop="menuType">
              <el-radio-group v-model="form.menuType">
                <el-radio label="M">目录</el-radio>
                <el-radio label="C">菜单</el-radio>
                <el-radio label="F">按钮</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" v-if="form.menuType != 'F'">
            <el-form-item label="菜单图标" prop="icon">
              <el-popover
                placement="bottom-start"
                width="460"
                trigger="click"
                @show="$refs['iconSelect'].reset()"
              >
                <IconSelect ref="iconSelect" @selected="selected" :active-icon="form.icon" />
                <el-input slot="reference" v-model="form.icon" placeholder="点击选择图标" readonly>
                  <svg-icon
                    v-if="form.icon"
                    slot="prefix"
                    :icon-class="form.icon"
                    style="width: 25px;"
                  />
                  <i v-else slot="prefix" class="el-icon-search el-input__icon" />
                </el-input>
              </el-popover>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item label="显示排序" prop="orderNum">
              <el-input-number v-model="form.orderNum" controls-position="right" :min="0" />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12">
            <el-form-item :label="menuNameLabel" prop="menuName">
              <el-input v-model="form.menuName" :placeholder="menuNamePlaceholder" />
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item :label="menuNameEnLabel" prop="menuNameEn">
              <el-input v-model="form.menuNameEn" :placeholder="menuNameEnPlaceholder" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.menuType == 'C'">
            <el-form-item prop="routeName">
              <el-input v-model="form.routeName" placeholder="请输入路由名称" />
              <span slot="label">
                <el-tooltip content="默认不填则和路由地址相同：如地址为：`user`，则名称为`User`（注意：为避免名字的冲突，特殊情况下请自定义，保证唯一性）" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                路由名称
              </span>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" v-if="form.menuType != 'F'">
            <el-form-item prop="isFrame">
              <span slot="label">
                <el-tooltip content="选择是外链则路由地址需要以`http(s)://`开头" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                是否外链
              </span>
              <el-radio-group v-model="form.isFrame">
                <el-radio label="0">是</el-radio>
                <el-radio label="1">否</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.menuType != 'F'">
            <el-form-item prop="path">
              <span slot="label">
                <el-tooltip content="访问的路由地址，如：`user`，如外网地址需内链访问则以`http(s)://`开头" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                路由地址
              </span>
              <el-input v-model="form.path" placeholder="请输入路由地址" />
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" v-if="form.menuType == 'C'">
            <el-form-item prop="component">
              <span slot="label">
                <el-tooltip content="访问的组件路径，如：`system/user/index`，默认在`views`目录下" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                组件路径
              </span>
              <el-input v-model="form.component" placeholder="请输入组件路径" />
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.menuType != 'M'">
            <el-form-item prop="perms">
              <el-input v-model="form.perms" placeholder="请输入权限标识" maxlength="100" />
              <span slot="label">
                <el-tooltip content="控制器中定义的权限字符，如：@PreAuthorize(`@ss.hasPermi('system:user:list')`)" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                权限字符
              </span>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" v-if="form.menuType == 'C'">
            <el-form-item prop="query">
              <el-input v-model="form.query" placeholder="请输入路由参数" maxlength="255" />
              <span slot="label">
                <el-tooltip content='访问路由的默认传递参数，如：`{"id": 1, "name": "ry"}`' placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                路由参数
              </span>
            </el-form-item>
          </el-col>
          <el-col :span="12" v-if="form.menuType == 'C'">
            <el-form-item prop="isCache">
              <span slot="label">
                <el-tooltip content="选择是则会被`keep-alive`缓存，需要匹配组件的`name`和地址保持一致" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                是否缓存
              </span>
              <el-radio-group v-model="form.isCache">
                <el-radio label="0">缓存</el-radio>
                <el-radio label="1">不缓存</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
        <el-row>
          <el-col :span="12" v-if="form.menuType != 'F'">
            <el-form-item prop="visible">
              <span slot="label">
                <el-tooltip content="选择隐藏则路由将不会出现在侧边栏，但仍然可以访问" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                显示状态
              </span>
              <el-radio-group v-model="form.visible">
                <el-radio
                  v-for="dict in dict.type.sys_show_hide"
                  :key="dict.value"
                  :label="dict.value"
                >{{dict.label}}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
          <el-col :span="12">
            <el-form-item prop="status">
              <span slot="label">
                <el-tooltip content="选择停用则路由将不会出现在侧边栏，也不能被访问" placement="top">
                <i class="el-icon-question"></i>
                </el-tooltip>
                菜单状态
              </span>
              <el-radio-group v-model="form.status">
                <el-radio
                  v-for="dict in dict.type.sys_normal_disable"
                  :key="dict.value"
                  :label="dict.value"
                >{{dict.label}}</el-radio>
              </el-radio-group>
            </el-form-item>
          </el-col>
        </el-row>
      </el-form>
      <div slot="footer" class="dialog-footer">
        <el-button type="primary" @click="submitForm">确 定</el-button>
        <el-button @click="cancel">取 消</el-button>
      </div>
    </el-dialog>
  </div>
</template>

<script>
import { listMenu, getMenu, delMenu, addMenu, updateMenu } from "@/api/system/menu"
import Treeselect from "@riophae/vue-treeselect"
import "@riophae/vue-treeselect/dist/vue-treeselect.css"
import IconSelect from "@/components/IconSelect"

export default {
  name: "Menu",
  dicts: ['sys_show_hide', 'sys_normal_disable'],
  components: { Treeselect, IconSelect },
  computed: {
    menuNameLabel() {
      return this.$i18n && this.$i18n.locale === 'en' ? 'Menu Name' : '菜单名称'
    },
    menuNamePlaceholder() {
      return this.$i18n && this.$i18n.locale === 'en' ? 'Enter menu name' : '请输入菜单名称'
    },
    menuNameEnLabel() {
      return this.$i18n && this.$i18n.locale === 'en' ? 'Menu Name (EN)' : '菜单英文名称'
    },
    menuNameEnPlaceholder() {
      return this.$i18n && this.$i18n.locale === 'en' ? 'Enter English name' : '请输入菜单英文名称'
    }
  },
  data() {
    return {
      // 遮罩层
      loading: true,
      // 显示搜索条件
      showSearch: true,
      // 菜单表格树数据
      menuList: [],
      // 菜单树选项
      menuOptions: [],
      // 弹出层标题
      title: "",
      // 是否显示弹出层
      open: false,
      // 是否展开，默认全部折叠
      isExpandAll: false,
      // 重新渲染表格状态
      refreshTable: true,
      // 查询参数
      queryParams: {
        menuName: undefined,
        visible: undefined
      },
      // 表单参数
      form: {},
      // 表单校验
      rules: {
        menuName: [
          { required: true, message: "菜单名称不能为空", trigger: "blur" }
        ],
        orderNum: [
          { required: true, message: "菜单顺序不能为空", trigger: "blur" }
        ],
        path: [
          { required: true, message: "路由地址不能为空", trigger: "blur" }
        ]
      }
    }
  },
  created() {
    this.getList()
  },
  methods: {
    // 选择图标
    selected(name) {
      this.form.icon = name
    },
    displayMenuName(row) {
      if (this.$i18n && this.$i18n.locale === 'en' && row.menuNameEn) {
        return row.menuNameEn
      }
      return row.menuName
    },
    /** 查询菜单列表 */
    getList() {
      this.loading = true
      listMenu(this.queryParams).then(response => {
        this.menuList = this.handleTree(response.data, "menuId")
        this.loading = false
      })
    },
    /** 转换菜单数据结构 */
    normalizer(node) {
      if (node.children && !node.children.length) {
        delete node.children
      }
      return {
        id: node.menuId,
        label: this.displayMenuName(node),
        children: node.children
      }
    },
    /** 查询菜单下拉树结构 */
    getTreeselect() {
      listMenu().then(response => {
        this.menuOptions = []
        const menuName = this.$i18n && this.$i18n.locale === 'en' ? 'Root' : '主类目'
        const menu = { menuId: 0, menuName, children: [] }
        menu.children = this.handleTree(response.data, "menuId")
        this.menuOptions.push(menu)
      })
    },
    // 取消按钮
    cancel() {
      this.open = false
      this.reset()
    },
    // 表单重置
    reset() {
      this.form = {
        menuId: undefined,
        parentId: 0,
        menuName: undefined,
        menuNameEn: undefined,
        icon: undefined,
        menuType: "M",
        orderNum: undefined,
        isFrame: "1",
        isCache: "0",
        visible: "0",
        status: "0"
      }
      this.resetForm("form")
    },
    /** 搜索按钮操作 */
    handleQuery() {
      this.getList()
    },
    /** 重置按钮操作 */
    resetQuery() {
      this.resetForm("queryForm")
      this.handleQuery()
    },
    /** 新增按钮操作 */
    handleAdd(row) {
      this.reset()
      this.getTreeselect()
      if (row != null && row.menuId) {
        this.form.parentId = row.menuId
      } else {
        this.form.parentId = 0
      }
      this.open = true
      this.title = "添加菜单"
    },
    /** 展开/折叠操作 */
    toggleExpandAll() {
      this.refreshTable = false
      this.isExpandAll = !this.isExpandAll
      this.$nextTick(() => {
        this.refreshTable = true
      })
    },
    /** 修改按钮操作 */
    handleUpdate(row) {
      this.reset()
      this.getTreeselect()
      getMenu(row.menuId).then(response => {
        this.form = response.data
        this.open = true
        this.title = "修改菜单"
      })
    },
    /** 提交按钮 */
    submitForm: function() {
      this.$refs["form"].validate(valid => {
        if (valid) {
          if (this.form.menuId != undefined) {
            updateMenu(this.form).then(response => {
              this.$modal.msgSuccess("修改成功")
              this.open = false
              this.getList()
            })
          } else {
            addMenu(this.form).then(response => {
              this.$modal.msgSuccess("新增成功")
              this.open = false
              this.getList()
            })
          }
        }
      })
    },
    /** 删除按钮操作 */
    handleDelete(row) {
      this.$modal.confirm('是否确认删除名称为"' + row.menuName + '"的数据项？').then(function() {
        return delMenu(row.menuId)
      }).then(() => {
        this.getList()
        this.$modal.msgSuccess("删除成功")
      }).catch(() => {})
    }
  }
}
</script>

// ruoyi-ui/src-react/pages/system/menu/index.jsx
import React, { useEffect, useMemo, useState } from 'react'
import {
  Button,
  Card,
  Form,
  Input,
  InputNumber,
  Modal,
  Popover,
  Radio,
  Row,
  Select,
  Space,
  Table,
  Tooltip,
  TreeSelect,
  message
} from 'antd'
import {
  PlusOutlined,
  SortAscendingOutlined,
  EditOutlined,
  DeleteOutlined,
  QuestionCircleOutlined
} from '@ant-design/icons'
import Cookies from 'js-cookie'
import RightToolbar from '@/components/RightToolbar'
import IconSelect from '@/components/IconSelect'
import SvgIcon from '@/components/SvgIcon'
import { listMenu, getMenu, delMenu, addMenu, updateMenu } from '@/api/system/menu'
import { getDicts } from '@/api/system/dict/data'
import { handleTree, parseTime } from '@/utils/ruoyi'
import { checkPermi } from '@/utils/permission'

const defaultQueryParams = {
  menuName: undefined,
  status: undefined
}

const defaultFormState = {
  menuId: undefined,
  parentId: 0,
  menuName: undefined,
  menuNameEn: undefined,
  icon: undefined,
  menuType: 'M',
  orderNum: undefined,
  isFrame: '1',
  isCache: '0',
  visible: '0',
  status: '0',
  path: undefined,
  routeName: undefined,
  component: undefined,
  perms: undefined,
  query: undefined,
  remark: undefined
}

const mapTreeSelectOptions = (items = []) => {
  return items.map((item) => ({
    title: item.menuName,
    value: item.menuId,
    key: item.menuId,
    children: item.children ? mapTreeSelectOptions(item.children) : []
  }))
}

const collectKeys = (nodes = []) => {
  const keys = []
  const travel = (list) => {
    list.forEach((item) => {
      keys.push(item.menuId)
      if (item.children && item.children.length > 0) {
        travel(item.children)
      }
    })
  }
  travel(nodes)
  return keys
}

const Menu = () => {
  const [loading, setLoading] = useState(false)
  const [showSearch, setShowSearch] = useState(true)
  const [menuList, setMenuList] = useState([])
  const [menuOptions, setMenuOptions] = useState([])
  const [open, setOpen] = useState(false)
  const [title, setTitle] = useState('')
  const [queryParams, setQueryParams] = useState({ ...defaultQueryParams })
  const [formData, setFormData] = useState({ ...defaultFormState })
  const [isExpandAll, setIsExpandAll] = useState(false)
  const [expandedKeys, setExpandedKeys] = useState([])
  const [dictStatus, setDictStatus] = useState([])
  const [dictVisible, setDictVisible] = useState([])
  const [form] = Form.useForm()

  const lang = Cookies.get('language')
  const isEnglish = lang === 'en'

  const menuNameLabel = isEnglish ? 'Menu Name' : '菜单名称'
  const menuNamePlaceholder = isEnglish ? 'Enter menu name' : '请输入菜单名称'
  const menuNameEnLabel = isEnglish ? 'Menu Name (EN)' : '菜单英文名称'
  const menuNameEnPlaceholder = isEnglish ? 'Enter English name' : '请输入菜单英文名称'

  const displayMenuName = (row) => {
    if (isEnglish && row.menuNameEn) return row.menuNameEn
    return row.menuName
  }

  const getList = async () => {
    setLoading(true)
    try {
      const res = await listMenu(queryParams)
      const treeData = handleTree(res.data || [], 'menuId')
      setMenuList(treeData)
      if (isExpandAll) {
        setExpandedKeys(collectKeys(treeData))
      }
    } finally {
      setLoading(false)
    }
  }

  const getTreeselect = async () => {
    const res = await listMenu()
    const treeData = handleTree(res.data || [], 'menuId')
    const rootLabel = isEnglish ? 'Root' : '主类目'
    const rootNode = { menuId: 0, menuName: rootLabel, children: treeData }
    setMenuOptions(mapTreeSelectOptions([rootNode]))
  }

  const fetchDicts = async () => {
    const [statusRes, visibleRes] = await Promise.all([
      getDicts('sys_normal_disable'),
      getDicts('sys_show_hide')
    ])
    setDictStatus(statusRes.data || [])
    setDictVisible(visibleRes.data || [])
  }

  const handleQuery = () => {
    getList()
  }

  const resetQuery = () => {
    setQueryParams({ ...defaultQueryParams })
    getList()
  }

  const handleAdd = async (row) => {
    setFormData({ ...defaultFormState, parentId: row?.menuId || 0 })
    form.setFieldsValue({ ...defaultFormState, parentId: row?.menuId || 0 })
    await getTreeselect()
    setOpen(true)
    setTitle('添加菜单')
  }

  const handleUpdate = async (row) => {
    await getTreeselect()
    const res = await getMenu(row.menuId)
    setFormData(res.data)
    form.setFieldsValue(res.data)
    setOpen(true)
    setTitle('修改菜单')
  }

  const handleDelete = (row) => {
    Modal.confirm({
      title: '系统提示',
      content: `是否确认删除名称为"${row.menuName}"的数据项？`,
      onOk: async () => {
        await delMenu(row.menuId)
        message.success('删除成功')
        getList()
      }
    })
  }

  const toggleExpandAll = () => {
    const next = !isExpandAll
    setIsExpandAll(next)
    setExpandedKeys(next ? collectKeys(menuList) : [])
  }

  const submitForm = async () => {
    const values = await form.validateFields()
    const payload = { ...formData, ...values }
    if (payload.menuId) {
      await updateMenu(payload)
      message.success('修改成功')
    } else {
      await addMenu(payload)
      message.success('新增成功')
    }
    setOpen(false)
    getList()
  }

  useEffect(() => {
    getList()
    fetchDicts()
  }, [])

  const columns = useMemo(() => [
    {
      title: menuNameLabel,
      dataIndex: 'menuName',
      width: 180,
      render: (_, record) => displayMenuName(record)
    },
    {
      title: '图标',
      dataIndex: 'icon',
      align: 'center',
      width: 100,
      render: (value) => <SvgIcon iconClass={value} />
    },
    {
      title: '排序',
      dataIndex: 'orderNum',
      width: 60
    },
    {
      title: '权限标识',
      dataIndex: 'perms',
      ellipsis: true
    },
    {
      title: '组件路径',
      dataIndex: 'component',
      ellipsis: true
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 80,
      render: (value) => {
        const target = dictStatus.find((item) => item.value === value)
        return target ? target.label : value
      }
    },
    {
      title: '创建时间',
      dataIndex: 'createTime',
      align: 'center',
      render: (value) => <span>{parseTime(value)}</span>
    },
    {
      title: '操作',
      align: 'center',
      render: (_, record) => (
        <Space>
          {checkPermi(['system:menu:edit']) && (
            <Button size="small" type="link" icon={<EditOutlined />} onClick={() => handleUpdate(record)}>
              修改
            </Button>
          )}
          {checkPermi(['system:menu:add']) && (
            <Button size="small" type="link" icon={<PlusOutlined />} onClick={() => handleAdd(record)}>
              新增
            </Button>
          )}
          {checkPermi(['system:menu:remove']) && (
            <Button size="small" type="link" icon={<DeleteOutlined />} danger onClick={() => handleDelete(record)}>
              删除
            </Button>
          )}
        </Space>
      )
    }
  ], [menuNameLabel, dictStatus])

  return (
    <Card>
      {showSearch && (
        <Form layout="inline" style={{ marginBottom: 16 }}>
          <Form.Item label={menuNameLabel}>
            <Input
              placeholder={menuNamePlaceholder}
              value={queryParams.menuName}
              onChange={(e) => setQueryParams({ ...queryParams, menuName: e.target.value })}
              onPressEnter={handleQuery}
            />
          </Form.Item>
          <Form.Item label="状态">
            <Select
              placeholder="菜单状态"
              allowClear
              value={queryParams.status}
              onChange={(value) => setQueryParams({ ...queryParams, status: value })}
              style={{ width: 200 }}
            >
              {dictStatus.map((item) => (
                <Select.Option key={item.value} value={item.value}>
                  {item.label}
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item>
            <Space>
              <Button type="primary" onClick={handleQuery}>搜索</Button>
              <Button onClick={resetQuery}>重置</Button>
            </Space>
          </Form.Item>
        </Form>
      )}

      <Row justify="space-between" style={{ marginBottom: 16 }}>
        <Space>
          {checkPermi(['system:menu:add']) && (
            <Button type="primary" icon={<PlusOutlined />} onClick={() => handleAdd()}>
              新增
            </Button>
          )}
          <Button icon={<SortAscendingOutlined />} onClick={toggleExpandAll}>
            展开/折叠
          </Button>
        </Space>
        <RightToolbar showSearch={showSearch} onShowSearchChange={setShowSearch} onQuery={getList} />
      </Row>

      <Table
        rowKey="menuId"
        loading={loading}
        dataSource={menuList}
        columns={columns}
        pagination={false}
        expandable={{
          expandedRowKeys: expandedKeys,
          onExpandedRowsChange: (keys) => setExpandedKeys(keys)
        }}
      />

      <Modal
        title={title}
        open={open}
        onCancel={() => setOpen(false)}
        onOk={submitForm}
        width={720}
        destroyOnClose
      >
        <Form form={form} layout="vertical" initialValues={formData}>
          <Form.Item name="parentId" label="上级菜单" rules={[{ required: true, message: '请选择上级菜单' }]}>
            <TreeSelect treeData={menuOptions} placeholder="选择上级菜单" treeDefaultExpandAll />
          </Form.Item>
          <Form.Item name="menuType" label="菜单类型" rules={[{ required: true, message: '请选择菜单类型' }]}>
            <Radio.Group>
              <Radio value="M">目录</Radio>
              <Radio value="C">菜单</Radio>
              <Radio value="F">按钮</Radio>
            </Radio.Group>
          </Form.Item>
          <Row gutter={16}>
            {formData.menuType !== 'F' && (
              <Form.Item name="icon" label="菜单图标" style={{ flex: 1, marginRight: 16 }}>
                <Popover content={<IconSelect value={formData.icon} onChange={(value) => {
                  setFormData(prev => ({ ...prev, icon: value }))
                  form.setFieldsValue({ icon: value })
                }} />} trigger="click">
                  <Input
                    readOnly
                    placeholder="点击选择图标"
                    value={formData.icon}
                    prefix={formData.icon ? <SvgIcon iconClass={formData.icon} /> : null}
                  />
                </Popover>
              </Form.Item>
            )}
            <Form.Item name="orderNum" label="显示排序" style={{ flex: 1 }}>
              <InputNumber min={0} style={{ width: '100%' }} />
            </Form.Item>
          </Row>
          <Row gutter={16}>
            <Form.Item name="menuName" label={menuNameLabel} style={{ flex: 1 }} rules={[{ required: true, message: '菜单名称不能为空' }]}>
              <Input placeholder={menuNamePlaceholder} />
            </Form.Item>
            <Form.Item name="menuNameEn" label={menuNameEnLabel} style={{ flex: 1 }}>
              <Input placeholder={menuNameEnPlaceholder} />
            </Form.Item>
            {formData.menuType === 'C' && (
              <Form.Item
                name="routeName"
                label={(
                  <Space>
                    <span>路由名称</span>
                    <Tooltip title="默认不填则和路由地址相同，特殊情况请保证唯一">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Input placeholder="请输入路由名称" />
              </Form.Item>
            )}
          </Row>
          <Row gutter={16}>
            {formData.menuType !== 'F' && (
              <Form.Item
                name="isFrame"
                label={(
                  <Space>
                    <span>是否外链</span>
                    <Tooltip title="选择是外链则路由地址需要以 http(s):// 开头">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Radio.Group>
                  <Radio value="0">是</Radio>
                  <Radio value="1">否</Radio>
                </Radio.Group>
              </Form.Item>
            )}
            {formData.menuType !== 'F' && (
              <Form.Item
                name="path"
                label={(
                  <Space>
                    <span>路由地址</span>
                    <Tooltip title="访问的路由地址，如 user 或 http(s)://">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
                rules={[{ required: true, message: '路由地址不能为空' }]}
              >
                <Input placeholder="请输入路由地址" />
              </Form.Item>
            )}
          </Row>
          <Row gutter={16}>
            {formData.menuType === 'C' && (
              <Form.Item
                name="component"
                label={(
                  <Space>
                    <span>组件路径</span>
                    <Tooltip title="访问的组件路径，如 system/user/index">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Input placeholder="请输入组件路径" />
              </Form.Item>
            )}
            {formData.menuType !== 'M' && (
              <Form.Item
                name="perms"
                label={(
                  <Space>
                    <span>权限字符</span>
                    <Tooltip title="控制器中定义的权限字符">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Input placeholder="请输入权限标识" maxLength={100} />
              </Form.Item>
            )}
          </Row>
          <Row gutter={16}>
            {formData.menuType === 'C' && (
              <Form.Item
                name="query"
                label={(
                  <Space>
                    <span>路由参数</span>
                    <Tooltip title='访问路由的默认参数，如 {"id":1,"name":"ry"}'>
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Input placeholder="请输入路由参数" maxLength={255} />
              </Form.Item>
            )}
            {formData.menuType === 'C' && (
              <Form.Item
                name="isCache"
                label={(
                  <Space>
                    <span>是否缓存</span>
                    <Tooltip title="选择是则会被 keep-alive 缓存">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Radio.Group>
                  <Radio value="0">缓存</Radio>
                  <Radio value="1">不缓存</Radio>
                </Radio.Group>
              </Form.Item>
            )}
          </Row>
          <Row gutter={16}>
            {formData.menuType !== 'F' && (
              <Form.Item
                name="visible"
                label={(
                  <Space>
                    <span>显示状态</span>
                    <Tooltip title="选择隐藏则路由不会出现在侧边栏">
                      <QuestionCircleOutlined />
                    </Tooltip>
                  </Space>
                )}
                style={{ flex: 1 }}
              >
                <Radio.Group>
                  {dictVisible.map((item) => (
                    <Radio key={item.value} value={item.value}>{item.label}</Radio>
                  ))}
                </Radio.Group>
              </Form.Item>
            )}
            <Form.Item
              name="status"
              label={(
                <Space>
                  <span>菜单状态</span>
                  <Tooltip title="选择停用则路由不会出现在侧边栏也不能访问">
                    <QuestionCircleOutlined />
                  </Tooltip>
                </Space>
              )}
              style={{ flex: 1 }}
            >
              <Radio.Group>
                {dictStatus.map((item) => (
                  <Radio key={item.value} value={item.value}>{item.label}</Radio>
                ))}
              </Radio.Group>
            </Form.Item>
          </Row>
        </Form>
      </Modal>
    </Card>
  )
}

export default Menu
